---
kind: pipeline
name: callisto-ui-nginx
type: kubernetes

platform:
  os: linux
  arch: amd64

environment:
  VERSION: latest-20220623

steps:
  - name: build_image
    pull: if-not-exists
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    environment:
      DOCKER_HOST: tcp://docker:2375
    commands:
      # wait for docker service to be up before running docker build
      - n=0; while [ "$n" -lt 60 ] && [ ! "$(docker stats --no-stream)" ]; do n=$(( n + 1 )); sleep 1; done
      - docker build -t docker-nginx-oss-s3-gateway:${VERSION} .
    when:
      event:
        - push

  - name: build_tag_ecr
    pull: if-not-exists
    image: plugins/ecr
    environment:
      AWS_REGION: eu-west-2
    settings:
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      repo: callisto/nginx-s3-gateway
      registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
      tags:
        - latest
        - ${VERSION}
    when:
      event:
        - tag

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    environment:
      DOCKER_TLS_CERTDIR: ""
