name: callisto-web

service:
  name: callisto-web
  port: 3000

replicaCount: 1

image:
  repo: quay.io/ukhomeofficedigital/
  name: callisto-nginx-s3-gateway
  version: latest

nginxs3proxy:
  s3server: s3.eu-west-2.amazonaws.com
  s3serverPort: 443
  s3serverProto: https
  s3region: eu-west-2
  s3style: virtual
  s3debug: false
  awsSigsVersion: 4
  allowDirectoryList: false
  proxyCacheValidOk: 5m
  proxyCacheValidNotFound: 1m
  proxyCacheValidForbidden: 30s
  provideIndexPage: true
  appendSlashForPossibleDirectory: false

env:
  s3secretRef: ho-callisto-dev-s3